project:
  type: website
  output-dir: docs

website:
  title: "Griffin Shelor"
  search: false
  navbar:
    background: "#8A8D8F"
    left:
      - href: index.qmd
        text: Home
        icon: house-door-fill
      - about/index.qmd
      - research/index.qmd
      # - href: projects/index.qmd
        # text: Projects
      # - href: VoA/index.qmd
      - text: VoA
        menu:
          - text: About the Vortex of Accuracy
            href: VoA/index.qmd
          - text: NFL VoA
            href: VoA/NFL/index.qmd
          - text: CFB VoA
            href: VoA/CFB/index.qmd
          - text: MCBB VoA
            href: VoA/MCBB/index.qmd
      - href: media/GShelor_CV.pdf
        text: CV
    tools:
      - icon: github
        href: https://github.com/gshelor

format:
  html:
    backgroundcolor: "#041E42"
    fontcolor: "#FFFFFF"
    linkcolor: "#FFC310"
    theme: solar
    css: styles.css
    toc: true

editor: source

