project:
  type: website
  output-dir: docs

website:
  title: "Griffin Shelor"
  search: false
  navbar:
    background: "#8A8D8F"
    left:
      - href: index.qmd
        text: Home
        icon: house-door-fill
      - about/index.qmd
      - projects/index.qmd
      # - href: projects/index.qmd
        # text: Projects
      - href: media/GShelor_CV.pdf
        text: CV
    tools:
      - icon: github
        href: https://github.com/gshelor

format:
  html:
    backgroundcolor: "#041E42"
    fontcolor: "#FFFFFF"
    linkcolor: "#FFC310"
    theme: cosmo
    css: styles.css
    toc: true

editor: source

