---
title: "About Me"
---

I am a geographer and data analyst who uses remote sensing and GIS to explore the relationships between snow and our changing climate.

As an undergraduate at Green Mountain College I fell in love with GIS and its power to help provide quality data to support more informed management decisions by stakeholders. I took this passion further when I worked on a team to study vegetation and water resource disturbance in support of a bison management strategy as part of a NASA DEVELOP project in the summer of 2018. This project both inspired me to begin thinking about the possibility of pursuing graduate research as well as gave me an introduction to the excitement of remote sensing. Over the next 2 years I worked as a Cartographic Technician for the U.S. Census Bureau, gaining an appreciation for social and economic geography as well as the importance of considering how people are impacted by policy. In April 2021 I was able to get back to my environmental roots by joining University of Vermont's Spatial Analysis Lab (SAL). At the SAL I worked on a variety of remote sensing projects, largely urban tree canopy (UTC) and land cover mapping projects. During my last year at the SAL, I was able to lead the editing effort on two wetlands mapping projects. This was a new challenge for me and introduced me to the intricacies of wetlands mapping and project management.

As a Masters student at the University of Nevada Reno (UNR) I modeled snow water equivalent (SWE) and used SHAP to identify how key predictors of peak SWE vary across different regions of the Western US and Alaska. This experience helped me come to love the process of working through challenging research problems and independently designing workflows for analyzing large, complex datasets.

I'm currently open to opportunities in either geospatial analysis/remote sensing or sports analytics and am willing to relocate if necessary, so feel free to reach out to me either via email or Linkedin!
